default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: menu_api_development
  username: postgres
  password: 123456
  host: localhost
  port: 5432

test:
  <<: *default
  database: menu_api_test
  username: postgres
  password: 123456
  host: localhost
  port: 5432

production:
  <<: *default
  database: menu_api_production
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '123456' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>



