development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "your_secret_key_base_here_change_in_production" %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "test_secret_key_base" %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>



